http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints: ["web"]
      middlewares: ["redirect-https"]
      service: "noop"

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"
